google_info :
  press :
    key    : 0Aiwzrc8lx93KdEpoYlZPa2tRU25FT1Fzb2s4Yi16UlE
    object : Press
    types  : ['Press']

  people :
    key    : 0Aiwzrc8lx93KdDJrQllra3VmQkx1OTNlclNCY0hIWFE
    object : Person
    types  : ['Current', 'Alumni']
    
  publications :
    key    : 0Aiwzrc8lx93KdFhudDZDZzdRTkVHQWtpUVNFd01xckE
    object : Publication
    types  : ['Publications']

flickr :
  hcc_photos:
    set: "72157646414725101"

data_directory : './_data'

credentials : 'spec/_secret_config.yml'
