google_info :
  press :
    key    : 0Aiwzrc8lx93KdEpoYlZPa2tRU25FT1Fzb2s4Yi16UlE
    object : Press
    types  : ['Press']

  people :
    key    : 0Aiwzrc8lx93KdDJrQllra3VmQkx1OTNlclNCY0hIWFE
    object : Person
    types  : ['Current', 'Alumni']

  projects :
    key    : 0AihuFDqjCvbedDMzS0FRc1hTT3JVY2lRT2pfekszY3c
    object : Project
    types  : ['Projects']
  publications :
    key    : 0Aiwzrc8lx93KdFhudDZDZzdRTkVHQWtpUVNFd01xckE
    object : Publication
    types  : ['Publications']

data_directory : './_data'

credentials : 'spec/_secret_config.yml'
